// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbh4nJJVTZpKyc3H_olXVZd5lx6-3uvy0',
    appId: '1:435495135282:android:1720d33d25cb6fbb76f42b',
    messagingSenderId: '435495135282',
    projectId: 'campus-find-d4646',
    storageBucket: 'campus-find-d4646.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBar3B2HO-HVC765gh7KMmpFLhKEByX0IE',
    appId: '1:435495135282:ios:3df3057392c87e5d76f42b',
    messagingSenderId: '435495135282',
    projectId: 'campus-find-d4646',
    storageBucket: 'campus-find-d4646.firebasestorage.app',
    iosBundleId: 'com.example.campusFind',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBar3B2HO-HVC765gh7KMmpFLhKEByX0IE',
    appId: '1:435495135282:ios:3df3057392c87e5d76f42b',
    messagingSenderId: '435495135282',
    projectId: 'campus-find-d4646',
    storageBucket: 'campus-find-d4646.firebasestorage.app',
    iosBundleId: 'com.example.campusFind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-lHIN621UlkkAD-B5mGlcsJDPbY_Qg4E',
    appId: '1:435495135282:web:942720020b740e9e76f42b',
    messagingSenderId: '435495135282',
    projectId: 'campus-find-d4646',
    authDomain: 'campus-find-d4646.firebaseapp.com',
    storageBucket: 'campus-find-d4646.firebasestorage.app',
    measurementId: 'G-BXQYFW7T3Q',
  );
}
